### ISSUE TITLE
Get underlying bitboard (possibly as a list?)

### ISSUE THREAD

**Issue by spohngellert-o** [DOBRO/binbo#12]
Hi, I am potentially looking to use this library for data analysis purposes in tandom with Nx libraries. I was wondering if there is a function I missed for getting the underlying game state as a bitboard. Thanks!

**Comment by DOBRO** [comment]
Hi, try  `binbo:game_state(Pid)`
https://github.com/DOBRO/binbo#game-state

You can find the keys of the map here
https://github.com/DOBRO/binbo/blob/master/include/binbo_position.hrl#L23-L42

They have prefix `bb`. E.g. `bbwp` - bitboard of white pawns, `bbwn` - bitboard of white knights, `bbbb` - bitboard of black bishops, etc.

**Comment by spohngellert-o** [comment]
:facepalm: Sorry I missed that. Think I have some handle of how to convert that into the format that I need. Thanks so much!
