### ISSUE TITLE
How do I get a list of piece positions?

### ISSUE THREAD

**Issue by JMS55** [DOBRO/binbo#2]

**Comment by JMS55** [comment]
I ended up solving this by parsing the result of get_fen().
```elixir
  defp parse_fen(fen, piece_list \\ []) do
    {c, tail} = String.next_grapheme(fen)
    case c do
      " " ->
        piece_list
      "/" ->
        parse_fen(tail, piece_list)
      "1" ->
        parse_fen(tail, piece_list ++ List.duplicate({nil, nil}, 1))
      "2" ->
        parse_fen(tail, piece_list ++ List.duplicate({nil, nil}, 2))
      "3" ->
        parse_fen(tail, piece_list ++ List.duplicate({nil, nil}, 3))
      "4" ->
        parse_fen(tail, piece_list ++ List.duplicate({nil, nil}, 4))
      "5" ->
        parse_fen(tail, piece_list ++ List.duplicate({nil, nil}, 5))
      "6" ->
        parse_fen(tail, piece_list ++ List.duplicate({nil, nil}, 6))
      "7" ->
        parse_fen(tail, piece_list ++ List.duplicate({nil, nil}, 7))
      "8" ->
        parse_fen(tail, piece_list ++ List.duplicate({nil, nil}, 8))
      "p" ->
        parse_fen(tail, piece_list ++ [{:pawn, :black}])
      "n" ->
        parse_fen(tail, piece_list ++ [{:knight, :black}])
      "b" ->
        parse_fen(tail, piece_list ++ [{:bishop, :black}])
      "r" ->
        parse_fen(tail, piece_list ++ [{:rook, :black}])
      "q" ->
        parse_fen(tail, piece_list ++ [{:queen, :black}])
      "k" ->
        parse_fen(tail, piece_list ++ [{:king, :black}])
      "P" ->
        parse_fen(tail, piece_list ++ [{:pawn, :white}])
      "N" ->
        parse_fen(tail, piece_list ++ [{:knight, :white}])
      "B" ->
        parse_fen(tail, piece_list ++ [{:bishop, :white}])
      "R" ->
        parse_fen(tail, piece_list ++ [{:rook, :white}])
      "Q" ->
        parse_fen(tail, piece_list ++ [{:queen, :white}])
      "K" ->
        parse_fen(tail, piece_list ++ [{:king, :white}])
    end
  end
```

**Comment by DOBRO** [comment]
Hi,

calling binbo:get_fen/1 before and parsing FEN causes significant overhead. There is a much faster solution based on the fact that we already know the bitboard of all pieces for any position. I'll see what I can do.

BTW, your function returns the list of tuples in format `[{piece, color}, ...]` but no information about the square.
I think it would be better to get something like `[{"e2", pawn, white}, ...]`.

**Comment by JMS55** [comment]
The way I did it, each position is implicit based on the list position (I iterate with Enum.with_index()), so I can just iterate over the list and display it, without corrying about skipping around.

**Comment by DOBRO** [comment]
BTW, why do you need the list of pieces? Which case would it be useful for?

**Comment by JMS55** [comment]
For displaying the board in a webapp I'm building. You can see how I want to iterate over a list of every piece position here https://github.com/JMS55/chessmatch/blob/master/lib/chessmatch_web/live/game_live.html.leex.

**Comment by DOBRO** [comment]
Why not to get the board rendered on the client side parsing FEN with javascript?

**Comment by JMS55** [comment]
It's to do everything with Elixir on the server imo.

**Comment by DOBRO** [comment]
Try `binbo:get_pieces_list(Pid, index)` or `binbo:get_pieces_list(Pid, notation)` from master branch.

I'll add docs later

**Comment by JMS55** [comment]
Works great, thank you!
