### ISSUE TITLE
Add move() function taking integers 0-63

### ISSUE THREAD

**Issue by JMS55** [DOBRO/binbo#3]

**Comment by DOBRO** [comment]
Describe please

**Comment by JMS55** [comment]
all_legal_moves() can provide moves as integers, but move() requires you to convert to a string like "e1:a2". It would be great to be able to use move() with integers as well, like move(server_pid, from, to).

**Comment by DOBRO** [comment]
Added fun `binbo:index_move/3,4`

Examples:
`binbo:index_move(Pid, From, To)`

`binbo:index_move(Pid, From, To, 'q')`
`binbo:index_move(Pid, From, To, 'r')`
`binbo:index_move(Pid, From, To, 'b')`
`binbo:index_move(Pid, From, To, 'n')`

**Comment by JMS55** [comment]
Thanks, works great! Feel free to close this now.
