### ISSUE TITLE
Add game_winner(), to manually end game with the given side the winner

### ISSUE THREAD

**Issue by JMS55** [DOBRO/binbo#4]

**Comment by DOBRO** [comment]
Please provide some description when you create an issue.

**Comment by JMS55** [comment]
Please add a function similar to game_draw() that allows you to manually stop the game, and assign a winner.

For instance, if two users are playing, and one disconnects, I would like to manually award the other the win. 

Another variant should probably be added to GameStatus, something like `{manual_winner, winner_color, reason}`.

**Comment by DOBRO** [comment]
Added function ```binbo:set_game_winner(Pid, Winner, Reason)```.

Example: ```binbo:set_game_winner(Pid, white, black_lost_on_time)```.

Actually you can pass any term for the Winner's value.

**Comment by JMS55** [comment]
Works great, thanks!
