### ISSUE TITLE
Improve game state

### ISSUE THREAD

**Issue by thewhisperinyourears** [DOBRO/binbo#5]
In a game. Can we improve on the game state so that if binbo:game_status(Pid) prints the result in a more chess idiomatic way. for example instead of replying {:ok, checkmate} something like {:ok, white_wins} perhaps we can even add a verbose option to binbo:game_status. or just add a new command binbo:game_result() #=> {:ok, white_wins} or if no result {:ok, nil}

**Comment by DOBRO** [comment]
Yes, we can.
I agree, `checkmate ` is a status that requires additional call of `binbo:side_to_move(Pid)` to get the winner.
So, looking forward )))

**Comment by thewhisperinyourears** [comment]
You beat me to this. Makes sense. So now we have game_status() #=> {:ok, checkmate, white_wins}. This is very useful!

**Comment by DOBRO** [comment]
Binbo 3.0.0 released including these changes. Enjoy :)
