### ISSUE TITLE
Distribute via Hex

### ISSUE THREAD

**Issue by LandonSchropp** [DOBRO/binbo#6]
It'd be awesome if this package was distributed via Hex so it could easily be incorporated into projects.

Thanks!

**Comment by DOBRO** [comment]
Hi,

did you miss this https://hex.pm/packages/binbo ?

**Comment by LandonSchropp** [comment]
I absolutely did. Sorry about that!

Would it be okay if I added that to the readme under the installation instructions?

Thanks!

**Comment by DOBRO** [comment]
You are welcome :)

**Comment by DOBRO** [comment]
... and I think it would be better to add _Installation_ section with instructions hot to add Binbo as a dependency for Erlang and Elixir apps (`rebar.config` and `mix.exs`)

**Comment by DOBRO** [comment]
Added `Installation` section

**Comment by LandonSchropp** [comment]
@DOBRO Sorry for the slow response on this. This fell off my radar a bit.

Thanks for adding these instructions!
