### ISSUE TITLE
Engine over TCP

### ISSUE THREAD

**Issue by ballPointPenguin** [DOBRO/binbo#7]
I love this library! Thanks for the great work.

I wonder if it's feasible to make use of an engine over TCP, such as stockfish in a docker container, hosted or otherwise.

Alternately I think I could co-locate binbo and stockfish in one container together.

**Comment by DOBRO** [comment]
It's definitely possible. I would write OTP application that contains TCP socket acceptor in front that transmits processed packets to Binbo, and Binbo communicates with Stockfish over UCI.

And yes, Binbo and Stockfish must be placed on the same machine/container. There is no way to create a connection between Binbo and the engine over TCP yet.

**Comment by DOBRO** [comment]
Since Binbo `4.0.0` TCP connections to remote engines are natively supported. 
I added some examples to `Quick start` section https://github.com/DOBRO/binbo#quickstart-uci-over-tcp

Enjoy!
